'use strict';

const FUNCTION_CODES = {
    READ_COILS: 0x01,
    READ_DISCRETE_INPUTS: 0x02,
    READ_HOLDING_REGISTERS: 0x03,
    READ_INPUT_REGISTERS: 0x04,
    WRITE_SINGLE_COIL: 0x05,
    WRITE_SINGLE_REGISTER: 0x06,
    REPORT_SERVER_ID: 0x11,
    READ_FILE_RECORD: 0x14,
    WRITE_FILE_RECORD: 0x15,
    MASK_WRITE_REGISTER: 0x16,
    READ_WRITE_MULTIPLE_REGISTERS: 0x17,
    READ_FIFO_QUEUE: 0x18,
    ENCAPSULATED_INTERFACE_TRANSPORT: 0x2B,
    WRITE_MULTIPLE_COILS: 0x0F,
    WRITE_MULTIPLE_REGISTERS: 0x10
};

const EXCEPTION_CODES = {
    ILLEGAL_FUNCTION: 0x01,
    ILLEGAL_DATA_ADDRESS: 0x02,
    ILLEGAL_DATA_VALUE: 0x03,
    SERVER_DEVICE_FAILURE: 0x04,
    ACKNOWLEDGE: 0x05,
    SERVER_DEVICE_BUSY: 0x06,
    MEMORY_PARITY_ERROR: 0x08,
    GATEWAY_PATH_UNAVAILABLE: 0x0A,
    GATEWAY_TARGET_DEVICE_FAILED_TO_RESPOND: 0x0B
};

const EXCEPTION_MESSAGES = {
    [EXCEPTION_CODES.ILLEGAL_FUNCTION]: 'Illegal Function',
    [EXCEPTION_CODES.ILLEGAL_DATA_ADDRESS]: 'Illegal Data Address',
    [EXCEPTION_CODES.ILLEGAL_DATA_VALUE]: 'Illegal Data Value',
    [EXCEPTION_CODES.SERVER_DEVICE_FAILURE]: 'Server Device Failure',
    [EXCEPTION_CODES.ACKNOWLEDGE]: 'Acknowledge',
    [EXCEPTION_CODES.SERVER_DEVICE_BUSY]: 'Server Device Busy',
    [EXCEPTION_CODES.MEMORY_PARITY_ERROR]: 'Memory Parity Error',
    [EXCEPTION_CODES.GATEWAY_PATH_UNAVAILABLE]: 'Gateway Path Unavailable',
    [EXCEPTION_CODES.GATEWAY_TARGET_DEVICE_FAILED_TO_RESPOND]: 'Gateway Target Device Failed to Respond'
};

const COIL_VALUES = {
    OFF: 0x0000,
    ON: 0xFF00
};

const LIMITS = {
    MAX_ADDRESS: 0xFFFF,
    MAX_COILS_READ: 2000,
    MAX_DISCRETE_INPUTS_READ: 2000,
    MAX_REGISTERS_READ: 125,
    MAX_COILS_WRITE: 1968,
    MAX_REGISTERS_WRITE: 123,
    MAX_PDU_SIZE: 253,
    MAX_FIFO_COUNT: 31,
    MAX_RW_READ_REGISTERS: 125,
    MAX_RW_WRITE_REGISTERS: 121,
    MAX_FILE_RECORD_LENGTH: 122,
    MAX_FILE_NUMBER: 0xFFFF,
    MAX_FILE_RECORD_NUMBER: 0x270F
};

const MBAP = {
    HEADER_LENGTH: 7,
    PROTOCOL_ID: 0x0000,
    DEFAULT_PORT: 502,
    DEFAULT_UNIT_ID: 1,
    DEFAULT_TIMEOUT: 5000
};

const MEI_TYPES = {
    READ_DEVICE_IDENTIFICATION: 0x0E
};

const DEVICE_ID_CODES = {
    BASIC: 0x01,
    REGULAR: 0x02,
    EXTENDED: 0x03,
    SPECIFIC: 0x04
};

const DEVICE_ID_OBJECTS = {
    VendorName: 0x00,
    ProductCode: 0x01,
    MajorMinorRevision: 0x02,
    VendorUrl: 0x03,
    ProductName: 0x04,
    ModelName: 0x05,
    UserApplicationName: 0x06
};

const FILE_RECORD_REFERENCE_TYPE = 0x06;

module.exports = {
    FUNCTION_CODES,
    EXCEPTION_CODES,
    EXCEPTION_MESSAGES,
    COIL_VALUES,
    LIMITS,
    MBAP,
    MEI_TYPES,
    DEVICE_ID_CODES,
    DEVICE_ID_OBJECTS,
    FILE_RECORD_REFERENCE_TYPE
};
